version: 0.2

env:
  variables:
    ENVIRONMENT: "production"
    
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing production dependencies
      
  pre_build:
    commands:
      - echo Pre-build phase started on `date`
      - echo Environment is $ENVIRONMENT
      - echo Running security scans
      
  build:
    commands:
      - echo Build phase started on `date`
      - echo Running comprehensive tests
      - echo Minifying and optimizing assets
      - echo Building production bundle
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Preparing production artifacts
      - echo Invalidating CloudFront cache
      
artifacts:
  files:
    - '**/*'
  name: portfolio-prod-$(date +%Y-%m-%d)