version: 0.2

env:
  variables:
    ENVIRONMENT: "development"
    
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies
      
  pre_build:
    commands:
      - echo Pre-build phase started on `date`
      - echo Environment is $ENVIRONMENT
      
  build:
    commands:
      - echo Build phase started on `date`
      - echo Running tests
      - echo Optimizing assets
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Preparing artifacts for $ENVIRONMENT
      
artifacts:
  files:
    - '**/*'
  name: portfolio-dev-$(date +%Y-%m-%d)